const SEARCH_BOOK = "SEARCH_BOOK";
const SEARCH_RESULT = "SEARCH_RESULT"
const BOOKS_STATUS = "BOOK_STATUS"
const UPDATED_BOOKS = "UPDATED_BOOKS"
const GET_ALL_BOOKS = "GET_All_BOOKS"

module.exports = {
    SEARCH_BOOK,
    SEARCH_RESULT,
    BOOKS_STATUS,
    UPDATED_BOOKS,
    GET_ALL_BOOKS
}